openapi: 3.0.3
info:
  title: Sample API
  description: This is a sample API for demonstration purposes.
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: Production server
paths:
  /users:
    get:
      summary: Get a list of users
      description: Retrieve a list of all users in the system.
      responses:
        '200':
          description: A JSON array of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                   
